spring:
  datasource:
    username: ${DB_USER:qiliblog_readwrite}
    password: ${DB_PASSWORD:qiliblog@1}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:qiliblog}?currentSchema=${DB_SCHEMA:qiliblog}&TimeZone=Asia/Shanghai
    hikari:
      schema: ${DB_SCHEMA:qiliblog}
  data:
    redis:
      host: localhost
      port: 6379
      password:

  mail:
    username:  # 邮箱
    password:  # 授权码
  liquibase:
    enabled: true
    default-schema: ${DB_SCHEMA:qiliblog}
    user: ${DB_OWNER_USER:qiliblog_owner}
    password: ${DB_OWNER_PASSWORD:qiliblog@1}

logging:
  file:
    name: ./log/${spring.application.name:qiliblog-server}.log
  level:
    com.zqqiliyc: info
    web: info
    root: warn
    sql: error

mybatis:
  provider:
    schema: ${DB_SCHEMA:qiliblog}
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
